#!/bin/bash

failures=0

cd "$( dirname "${BASH_SOURCE[0]}" )"
cd ../
source ./localize.sh

function run_step    { >&2 echo -e "\033[1m\033[34m* $1\033[0m"; }
function run_substep { >&2 echo -e "\033[1m\033[36m* $1\033[0m"; }
function run_success { >&2 echo -e "\033[1m\033[32m* $1\033[0m"; }

run_step "Starting Mapnik tests"
# mapnik-settings.env is an optional file to store
# environment variables that should be used before
# running tests like PROJ_LIB, GDAL_DATA, and ICU_DATA
# These do not normally need to be set except when
# building against binary versions of dependencies like
# done via bootstrap.sh
if [[ -f mapnik-settings.env ]]; then
    run_substep "Inheriting from mapnik-settings.env"
    source mapnik-settings.env
fi

run_substep "Running C++ Unit tests..."
./test/unit/run
failures=$((failures+$?))

run_substep "Running standalone C++ tests..."
if [ -n "$(find test/standalone/ -maxdepth 1 -name '*-bin' -print -quit)" ]; then
    for FILE in test/standalone/*-bin; do 
        ${FILE};
      failures=$((failures+$?))
    done
fi

run_substep "Running visual tests..."
./test/visual/run
failures=$((failures+$?))

exit $failures
