#!/bin/sh

failures=0

source localize.sh

echo "*** Running visual tests..."
#python tests/visual_tests/test.py -q
#failures=$((failures+$?))

echo "*** Running C++ tests..."
for FILE in Release/*_test; do 
	${FILE} -d .;
  failures=$((failures+$?))
done

echo

#echo "*** Running python tests..."
#python tests/run_tests.py -q
#failures=$((failures+$?))

exit $failures
