#!/bin/sh

failures=0

PYTHON=${PYTHON:-python}

echo "*** Running visual tests..."
$PYTHON tests/visual_tests/test.py -q
failures=$((failures+$?))

echo "*** Running C++ tests..."
for FILE in tests/cpp_tests/*-bin; do 
	${FILE} -q -d .;
  failures=$((failures+$?))
done

echo

echo "*** Running python tests..."
$PYTHON tests/run_tests.py -q
failures=$((failures+$?))

exit $failures
