#
# This file is part of Mapnik (c++ mapping toolkit)
#
# Copyright (C) 2007 Artem Pavlenko, Jean-Francois Doyon
#
# Mapnik is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# $Id$

Import ('env')

prefix = env['PREFIX']
install_prefix = env['DESTDIR'] + '/' + prefix

ogr_src = Split(
	"""
	ogr_converter.cpp
	ogr_datasource.cpp
	ogr_featureset.cpp      
	ogr_index_featureset.cpp
	"""
        )

libraries = [env['PLUGINS']['ogr']['lib']]

if env['PLATFORM'] == 'Darwin':
    if env['HAS_BOOST_SYSTEM']:
        boost_system = 'boost_system%s' % env['BOOST_APPEND']
        libraries.append(boost_system)
    libraries.append('mapnik')
    libraries.append(env['ICU_LIB_NAME'])
    libraries.append('boost_iostreams%s' % env['BOOST_APPEND'])

ogr_inputdriver = env.SharedLibrary('ogr', source=ogr_src, SHLIBPREFIX='', SHLIBSUFFIX='.input', LIBS=libraries)

env.Install(install_prefix + '/' + env['LIBDIR_SCHEMA'] + env['LIB_DIR_NAME'] + '/input', ogr_inputdriver)
env.Alias('install', install_prefix + '/' + env['LIBDIR_SCHEMA'] + env['LIB_DIR_NAME'] + '/input')
