#include "catch.hpp"

#include <mapnik/agg_renderer.hpp>
#include <mapnik/expression.hpp>
#include <mapnik/feature_factory.hpp>
#include <mapnik/feature_type_style.hpp>
#include <mapnik/image.hpp>
#include <mapnik/image_filter_types.hpp>
#include <mapnik/layer.hpp>
#include <mapnik/map.hpp>
#include <mapnik/memory_datasource.hpp>
#include <mapnik/symbolizer.hpp>

namespace {

std::shared_ptr<mapnik::memory_datasource> polygon_datasource(double x)
{
    mapnik::parameters params;
    params["type"] = "memory";
    auto datasource = std::make_shared<mapnik::memory_datasource>(params);
    auto feature = mapnik::feature_factory::create(std::make_shared<mapnik::context_type>(), 1);
    mapnik::geometry::polygon<double> polygon;
    polygon.push_back({{x, 20}, {x + 20, 20}, {x + 20, 40}, {x, 40}, {x, 20}});
    feature->set_geometry(std::move(polygon));
    datasource->push(feature);
    return datasource;
}

} // namespace

TEST_CASE("Layer buffer reuse clears pixels painted by child layers")
{
    mapnik::Map map(100, 100, "+proj=longlat +datum=WGS84 +no_defs");
    for (std::string const name : {"red", "blue", "unmatched"})
    {
        mapnik::feature_type_style style;
        mapnik::rule rule;
        mapnik::polygon_symbolizer symbolizer;
        mapnik::put(symbolizer, mapnik::keys::fill, mapnik::color(name == "blue" ? "blue" : "red"));
        rule.append(std::move(symbolizer));
        if (name == "unmatched")
            rule.set_filter(mapnik::parse_expression("false"));
        style.add_rule(std::move(rule));
        map.insert_style(name, std::move(style));
    }

    mapnik::layer parent("parent", map.srs());
    parent.set_datasource(polygon_datasource(10));
    parent.add_style("unmatched");
    parent.set_opacity(0.5);

    mapnik::layer child("child", map.srs());
    child.set_datasource(polygon_datasource(10));
    child.add_style("red");
    child.set_opacity(0.5);
    parent.add_layer(std::move(child));
    map.add_layer(std::move(parent));

    // This layer reuses the parent's buffer and paints a disjoint polygon.
    mapnik::layer next("next", map.srs());
    next.set_datasource(polygon_datasource(60));
    next.add_style("blue");
    next.set_opacity(0.5);
    map.add_layer(std::move(next));

    map.zoom_to_box({0, 0, 100, 100});
    mapnik::image_rgba8 image(100, 100);
    mapnik::agg_renderer<mapnik::image_rgba8> renderer(map, image);
    renderer.apply();

    CHECK(image.get_row(70)[20] == 0x400000ff);
    CHECK(image.get_row(70)[70] == 0x7fff0000);
    CHECK(image.get_row(70)[50] == 0);
}

TEST_CASE("Layer buffer reuse clears pixels generated by image filters")
{
    for (std::string const mode : {"image filters", "direct image filters", "image filters with src"})
    {
        CAPTURE(mode);
        mapnik::Map map(100, 100, "+proj=longlat +datum=WGS84 +no_defs");
        for (std::string const name : {"filtered", "blue"})
        {
            mapnik::feature_type_style style;
            mapnik::rule rule;
            mapnik::polygon_symbolizer symbolizer;
            mapnik::put(symbolizer, mapnik::keys::fill, mapnik::color("blue"));
            rule.append(std::move(symbolizer));
            if (name == "filtered")
            {
                rule.set_filter(mapnik::parse_expression("false"));
                auto& filters = mode == "direct image filters" ? style.direct_image_filters() : style.image_filters();
                // This filter makes transparent input opaque gray even though no rule matched.
                filters.emplace_back(mapnik::filter::x_gradient{});
                if (mode == "image filters with src")
                    style.set_comp_op(mapnik::src);
            }
            else
            {
                // Reuse the filtered style's buffer as well as its layer's buffer.
                style.set_opacity(0.5);
            }
            style.add_rule(std::move(rule));
            map.insert_style(name, std::move(style));
        }

        mapnik::layer filtered("filtered", map.srs());
        filtered.set_datasource(polygon_datasource(10));
        filtered.add_style("filtered");
        filtered.set_opacity(0.5);
        map.add_layer(std::move(filtered));

        // Reusing the filtered layer's buffer must not composite its gray background twice.
        mapnik::layer next("next", map.srs());
        next.set_datasource(polygon_datasource(60));
        next.add_style("blue");
        next.set_opacity(0.5);
        map.add_layer(std::move(next));

        map.zoom_to_box({0, 0, 100, 100});
        mapnik::image_rgba8 image(100, 100);
        mapnik::agg_renderer<mapnik::image_rgba8> renderer(map, image);
        renderer.apply();

        CHECK(image.get_row(70)[20] == 0x7f808080);
        CHECK(image.get_row(70)[70] == 0x9fb34c4c);
    }
}
