#  This file is part of Mapnik (c++ mapping toolkit)
#  Copyright (C) 2005 Artem Pavlenko
#
#  Mapnik is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# $Id$


Import ('env')

prefix = env['PREFIX']
boost_root = env['BOOST_ROOT']

raster_src = Split(
	"""
	raster_datasource.cpp
	raster_featureset.cpp
	raster_info.cpp      
	"""
        )
headers = ['#include',boost_root]
raster_datasource = env.SharedLibrary('raster',source=raster_src,SHLIBPREFIX='',CPPPATH=headers)
env.Install(prefix + '/datasources',raster_datasource)
env.Alias("install",prefix + '/datasources')
