#mapnik 

Import ('env')

prefix = env['PREFIX']
boost_root = env['BOOST_ROOT']
agg_root = env['AGG_ROOT']
agg_headers = agg_root + '/include'

shape_src = Split(
	"""
        dbffile.cpp
        shape.cpp
        shape_featureset.cpp
        shapefile.cpp
        shape_index_featureset.cpp
        shape_io.cpp
        shp_index.cpp
	"""
        )

headers = ['#include',boost_root,agg_headers]

shape_datasource = env.SharedLibrary('shape',source=shape_src,SHLIBPREFIX='',CPPPATH=headers)
env.Install(prefix+"/datasources",shape_datasource)

