/* config.hh.  Generated by configure.  */
/* config.hh.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "shapeindex"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bugs@shapeindex"

/* Define to the full name of this package. */
#define PACKAGE_NAME "shapeindex"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "shapeindex 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "shapeindex"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Version number of package */
#define VERSION "0.1"
