#  This file is part of Mapnik (c++ mapping toolkit)
#  Copyright (C) 2005 Artem Pavlenko
#
#  Mapnik is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# $Id$

import glob

Import ('env')

prefix = env['PREFIX']
boost_root = env['BOOST_ROOT']
boost_po_src_dir = boost_root + "/libs/program_options/src/"
boost_po_src = glob.glob (boost_po_src_dir + '*.cpp')

lib_boost_filesystem = env.StaticLibrary('libboost-program-options',boost_po_src,CPPPATH=boost_root)

source = Split(
    """
    shapeindex.cpp
    #src/envelope.cpp
    #datasources/shape/shapefile.cpp
    """
    )

headers = ["#include","#datasources/shape",boost_root]
libraries = ['boost-program-options']
libpaths = ['.']

shapeindex = env.Program("shapeindex",source,CPPPATH=headers,LIBS=libraries,LIBPATH=libpaths)
env.Install(prefix+"/bin",shapeindex)
env.Alias("install",prefix + '/bin')
