#  This file is part of Mapnik (c++ mapping toolkit)
#  Copyright (C) 2005 Artem Pavlenko, Jean-Francois Doyon
#
#  Mapnik is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# $Id$

import glob

Import('env')

prefix = env['PREFIX']

libraries = ['agg'] + env['LIBS']

linkflags = '-Wl,-rpath-link,. -Wl,-soname,libmapnik.so'

source = Split(
    """
    mapnik.cpp
    datasource_cache.cpp
    envelope.cpp
    graphics.cpp
    image_reader.cpp
    image_util.cpp
    layer.cpp
    map.cpp
    memory.cpp
    params.cpp
    plugin.cpp
    png_reader.cpp
    text.cpp
    tiff_reader.cpp
    wkb.cpp
    agg_renderer.cpp
    point_symbolizer.cpp
    polygon_pattern_symbolizer.cpp
    line_pattern_symbolizer.cpp
    font_engine_freetype.cpp
    """
    )
#render.cpp
#line_symbolizer.cpp
#    line_pattern_symbolizer.cpp
#    polygon_symbolizer.cpp
#    polygon_pattern_symbolizer.cpp
#    image_symbolizer.cpp

mapnik = env.SharedLibrary('mapnik', source, LIBS=libraries, LINKFLAGS=linkflags)

env.Alias(target='install', source=env.Install(prefix+'/lib', mapnik))
includes = glob.glob('../include' + '/*.hpp')
env.Alias(target='install', source=env.Install(prefix+'/include/mapnik', includes))
