#
# This file is part of Mapnik (c++ mapping toolkit)
#
# Copyright (C) 2006 Artem Pavlenko, Jean-Francois Doyon
#
# Mapnik is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# $Id$

import glob

Import ('env')

prefix = env['PREFIX']
install_prefix = env['DESTDIR'] + '/' + prefix

source = Split(
    """
    shapeindex.cpp
    #src/envelope.cpp
    #plugins/input/shape/shapefile.cpp
    """
    )

headers = ['#plugins/input/shape'] + env['CPPPATH'] 

boost_program_options = 'boost_program_options%s' % env['BOOST_APPEND']
boost_iostreams  = 'boost_iostreams%s' % env['BOOST_APPEND']
boost_filesystem = 'boost_filesystem%s' % env['BOOST_APPEND']
libraries =  [boost_program_options,boost_iostreams,boost_filesystem]

boost_system = 'boost_system%s' % env['BOOST_APPEND']

if env['HAS_BOOST_SYSTEM']:
    libraries.append(boost_system)


shapeindex = env.Program('shapeindex', source, CPPPATH=headers, LIBS=libraries)

env.Install(install_prefix + '/bin', shapeindex)
env.Alias('install', install_prefix + '/bin')
