name: MacOS

on:
  workflow_call:
    inputs:
      VCPKG_SHA:
        required: true
        type: string
      VCPKG_NUGET_REPOSITORY:
        required: true
        type: string
      NUGET_REGISTRY:
        required: true
        type: string
      NUGET_USERNAME:
        required: true
        type: string
    secrets:
      NUGET_REGISTRY_PAT:
        required: true

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  UPDATE: 1
  preset: macos-ci
  mono: mono

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install required system packages
        run: |
          brew install automake ninja

      - name: checkout mapnik
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: checkout vcpkg
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: ${{ inputs.VCPKG_SHA }}
          path: vcpkg

      - name: "Setup vcpkg"
        shell: bash
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: "Setup NuGet Credentials"
        shell: "bash"
        run: >
          ${{ env.mono }} `${{ github.workspace }}/vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "${{ env.NUGET_REGISTRY }}"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ env.NUGET_USERNAME }}"
          -password "${{ secrets.NUGET_REGISTRY_PAT }}"

      - name: "Setup NuGet apikey"
        shell: "bash"
        run: >
          ${{ env.mono }} `${{ github.workspace }}/vcpkg/vcpkg fetch nuget | tail -n 1`
          setapikey "${{ secrets.NUGET_REGISTRY_PAT }}" -Source "${{ env.NUGET_REGISTRY }}"

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake --preset=${{ env.preset }}

      - name: Build
        run: cmake --build --preset ${{ env.preset }}

      - name: Test
        run: ctest --preset ${{ env.preset }}

      - name: Package
        run: cmake --build --preset ${{ env.preset }} --target package

      - uses: actions/upload-artifact@v2
        with:
          name: macos-mapnik-artifact
          path: build/*-ci/mapnik-*.tar.gz
          retention-days: 2
