name: MacOS

on:
  workflow_call:
    secrets:
      VCPKG_NUGET_CI:
        required: true

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"
  VCPKG_NUGET_REPOSITORY: https://github.com/mathisloge/vcpkg-nuget.git
  UPDATE: 1
  preset: macos-ci
  mono: mono

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install required system packages
        run: |
          brew install automake ninja

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/checkout@v2
        with:
          repository: "microsoft/vcpkg"
          ref: 431d3810aa9241aed49b14367be417f225d2af5e
          path: vcpkg

      - name: "Setup NuGet Credentials"
        shell: "bash"
        run: >
          ${{ env.mono }} `vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/mathisloge/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "mathisloge"
          -password "${{ secrets.VCPKG_NUGET_CI }}"

      - name: "Setup NuGet apikey"
        shell: "bash"
        run: >
          ${{ env.mono }} `vcpkg/vcpkg fetch nuget | tail -n 1`
          setapikey "${{ secrets.VCPKG_NUGET_CI }}" -Source "https://nuget.pkg.github.com/mathisloge/index.json"

      - name: Configure CMake
        run: cmake -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake --preset=${{ env.preset }}

      - name: Build
        run: cmake --build --preset ${{ env.preset }}

      - name: Test
        run: ctest --preset ${{ env.preset }}

      - name: Package
        run: cmake --build --preset ${{ env.preset }} --target package

      - uses: actions/upload-artifact@v2
        with:
          name: macos-mapnik-artifact
          path: build/*-ci/mapnik-*.tar.gz
          retention-days: 2
