name: MacOS

on:
  workflow_call:

env:
  UPDATE: 1
  preset: macos-ci
  mono: mono

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install required system packages
        run: |
          brew install automake ninja icu4c boost freetype harfbuzz libxml2 libpng jpeg libtiff webp cairo proj libpq gdal

      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Configure CMake
        run: cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/icu4c:/usr/local/opt/libxml2 --preset=${{ env.preset }}

      - name: Build
        run: cmake --build --preset ${{ env.preset }}

      - name: Test
        run: ctest --preset ${{ env.preset }}

      - name: Package
        run: cmake --build --preset ${{ env.preset }} --target package

      - uses: actions/upload-artifact@v2
        with:
          name: macos-mapnik-artifact
          path: build/*-ci/mapnik-*.tar.gz
          retention-days: 2
