
HEADERS += \
  $$PWD/../deps/agg/include/agg_alpha_mask_u8.h \
  $$PWD/../deps/agg/include/agg_arc.h \
  $$PWD/../deps/agg/include/agg_array.h \
  $$PWD/../deps/agg/include/agg_arrowhead.h \
  $$PWD/../deps/agg/include/agg_basics.h \
  $$PWD/../deps/agg/include/agg_bezier_arc.h \
  $$PWD/../deps/agg/include/agg_bitset_iterator.h \
  $$PWD/../deps/agg/include/agg_blur.h \
  $$PWD/../deps/agg/include/agg_bounding_rect.h \
  $$PWD/../deps/agg/include/agg_bspline.h \
  $$PWD/../deps/agg/include/agg_clip_liang_barsky.h \
  $$PWD/../deps/agg/include/agg_color_gray.h \
  $$PWD/../deps/agg/include/agg_color_rgba.h \
  $$PWD/../deps/agg/include/agg_config.h \
  $$PWD/../deps/agg/include/agg_conv_adaptor_vcgen.h \
  $$PWD/../deps/agg/include/agg_conv_adaptor_vpgen.h \
  $$PWD/../deps/agg/include/agg_conv_bspline.h \
  $$PWD/../deps/agg/include/agg_conv_clip_polygon.h \
  $$PWD/../deps/agg/include/agg_conv_clip_polyline.h \
  $$PWD/../deps/agg/include/agg_conv_close_polygon.h \
  $$PWD/../deps/agg/include/agg_conv_concat.h \
  $$PWD/../deps/agg/include/agg_conv_contour.h \
  $$PWD/../deps/agg/include/agg_conv_curve.h \
  $$PWD/../deps/agg/include/agg_conv_dash.h \
  $$PWD/../deps/agg/include/agg_conv_gpc.h \
  $$PWD/../deps/agg/include/agg_conv_marker_adaptor.h \
  $$PWD/../deps/agg/include/agg_conv_marker.h \
  $$PWD/../deps/agg/include/agg_conv_segmentator.h \
  $$PWD/../deps/agg/include/agg_conv_shorten_path.h \
  $$PWD/../deps/agg/include/agg_conv_smooth_poly1.h \
  $$PWD/../deps/agg/include/agg_conv_stroke.h \
  $$PWD/../deps/agg/include/agg_conv_transform.h \
  $$PWD/../deps/agg/include/agg_conv_unclose_polygon.h \
  $$PWD/../deps/agg/include/agg_curves.h \
  $$PWD/../deps/agg/include/agg_dda_line.h \
  $$PWD/../deps/agg/include/agg_ellipse_bresenham.h \
  $$PWD/../deps/agg/include/agg_ellipse.h \
  $$PWD/../deps/agg/include/agg_embedded_raster_fonts.h \
  $$PWD/../deps/agg/include/agg_font_cache_manager.h \
  $$PWD/../deps/agg/include/agg_gamma_functions.h \
  $$PWD/../deps/agg/include/agg_gamma_lut.h \
  $$PWD/../deps/agg/include/agg_glyph_raster_bin.h \
  $$PWD/../deps/agg/include/agg_gradient_lut.h \
  $$PWD/../deps/agg/include/agg_gsv_text.h \
  $$PWD/../deps/agg/include/agg_image_accessors.h \
  $$PWD/../deps/agg/include/agg_image_filters.h \
  $$PWD/../deps/agg/include/agg_line_aa_basics.h \
  $$PWD/../deps/agg/include/agg_math.h \
  $$PWD/../deps/agg/include/agg_math_stroke.h \
  $$PWD/../deps/agg/include/agg_path_length.h \
  $$PWD/../deps/agg/include/agg_path_storage.h \
  $$PWD/../deps/agg/include/agg_path_storage_integer.h \
  $$PWD/../deps/agg/include/agg_pattern_filters_rgba.h \
  $$PWD/../deps/agg/include/agg_pixfmt_amask_adaptor.h \
  $$PWD/../deps/agg/include/agg_pixfmt_gray.h \
  $$PWD/../deps/agg/include/agg_pixfmt_rgba.h \
  $$PWD/../deps/agg/include/agg_pixfmt_rgb.h \
  $$PWD/../deps/agg/include/agg_pixfmt_rgb_packed.h \
  $$PWD/../deps/agg/include/agg_pixfmt_transposer.h \
  $$PWD/../deps/agg/include/agg_rasterizer_cells_aa.h \
  $$PWD/../deps/agg/include/agg_rasterizer_compound_aa.h \
  $$PWD/../deps/agg/include/agg_rasterizer_outline_aa.h \
  $$PWD/../deps/agg/include/agg_rasterizer_outline.h \
  $$PWD/../deps/agg/include/agg_rasterizer_scanline_aa.h \
  $$PWD/../deps/agg/include/agg_rasterizer_sl_clip.h \
  $$PWD/../deps/agg/include/agg_renderer_base.h \
  $$PWD/../deps/agg/include/agg_renderer_markers.h \
  $$PWD/../deps/agg/include/agg_renderer_mclip.h \
  $$PWD/../deps/agg/include/agg_renderer_outline_aa.h \
  $$PWD/../deps/agg/include/agg_renderer_outline_image.h \
  $$PWD/../deps/agg/include/agg_renderer_primitives.h \
  $$PWD/../deps/agg/include/agg_renderer_raster_text.h \
  $$PWD/../deps/agg/include/agg_renderer_scanline.h \
  $$PWD/../deps/agg/include/agg_rendering_buffer_dynarow.h \
  $$PWD/../deps/agg/include/agg_rendering_buffer.h \
  $$PWD/../deps/agg/include/agg_rounded_rect.h \
  $$PWD/../deps/agg/include/agg_scanline_bin.h \
  $$PWD/../deps/agg/include/agg_scanline_boolean_algebra.h \
  $$PWD/../deps/agg/include/agg_scanline_p.h \
  $$PWD/../deps/agg/include/agg_scanline_storage_aa.h \
  $$PWD/../deps/agg/include/agg_scanline_storage_bin.h \
  $$PWD/../deps/agg/include/agg_scanline_u.h \
  $$PWD/../deps/agg/include/agg_shorten_path.h \
  $$PWD/../deps/agg/include/agg_simul_eq.h \
  $$PWD/../deps/agg/include/agg_span_allocator.h \
  $$PWD/../deps/agg/include/agg_span_converter.h \
  $$PWD/../deps/agg/include/agg_span_gouraud_gray.h \
  $$PWD/../deps/agg/include/agg_span_gouraud.h \
  $$PWD/../deps/agg/include/agg_span_gouraud_rgba.h \
  $$PWD/../deps/agg/include/agg_span_gradient_alpha.h \
  $$PWD/../deps/agg/include/agg_span_gradient.h \
  $$PWD/../deps/agg/include/agg_span_image_filter_gray.h \
  $$PWD/../deps/agg/include/agg_span_image_filter.h \
  $$PWD/../deps/agg/include/agg_span_image_filter_rgba.h \
  $$PWD/../deps/agg/include/agg_span_image_filter_rgb.h \
  $$PWD/../deps/agg/include/agg_span_interpolator_adaptor.h \
  $$PWD/../deps/agg/include/agg_span_interpolator_linear.h \
  $$PWD/../deps/agg/include/agg_span_interpolator_persp.h \
  $$PWD/../deps/agg/include/agg_span_interpolator_trans.h \
  $$PWD/../deps/agg/include/agg_span_pattern_gray.h \
  $$PWD/../deps/agg/include/agg_span_pattern_rgba.h \
  $$PWD/../deps/agg/include/agg_span_pattern_rgb.h \
  $$PWD/../deps/agg/include/agg_span_solid.h \
  $$PWD/../deps/agg/include/agg_span_subdiv_adaptor.h \
  $$PWD/../deps/agg/include/agg_trans_affine.h \
  $$PWD/../deps/agg/include/agg_trans_bilinear.h \
  $$PWD/../deps/agg/include/agg_trans_double_path.h \
  $$PWD/../deps/agg/include/agg_trans_lens.h \
  $$PWD/../deps/agg/include/agg_trans_perspective.h \
  $$PWD/../deps/agg/include/agg_trans_single_path.h \
  $$PWD/../deps/agg/include/agg_trans_viewport.h \
  $$PWD/../deps/agg/include/agg_trans_warp_magnifier.h \
  $$PWD/../deps/agg/include/agg_vcgen_bspline.h \
  $$PWD/../deps/agg/include/agg_vcgen_contour.h \
  $$PWD/../deps/agg/include/agg_vcgen_dash.h \
  $$PWD/../deps/agg/include/agg_vcgen_markers_term.h \
  $$PWD/../deps/agg/include/agg_vcgen_smooth_poly1.h \
  $$PWD/../deps/agg/include/agg_vcgen_stroke.h \
  $$PWD/../deps/agg/include/agg_vcgen_vertex_sequence.h \
  $$PWD/../deps/agg/include/agg_vertex_sequence.h \
  $$PWD/../deps/agg/include/agg_vpgen_clip_polygon.h \
  $$PWD/../deps/agg/include/agg_vpgen_clip_polyline.h \
  $$PWD/../deps/agg/include/agg_vpgen_segmentator.h

SOURCES += \
  $$PWD/../deps/agg/src/agg_arc.cpp \
  $$PWD/../deps/agg/src/agg_arrowhead.cpp \
  $$PWD/../deps/agg/src/agg_bezier_arc.cpp \
  $$PWD/../deps/agg/src/agg_bspline.cpp \
  $$PWD/../deps/agg/src/agg_curves.cpp \
  $$PWD/../deps/agg/src/agg_embedded_raster_fonts.cpp \
  $$PWD/../deps/agg/src/agg_gsv_text.cpp \
  $$PWD/../deps/agg/src/agg_image_filters.cpp \
  $$PWD/../deps/agg/src/agg_line_aa_basics.cpp \
  $$PWD/../deps/agg/src/agg_line_profile_aa.cpp \
  $$PWD/../deps/agg/src/agg_rounded_rect.cpp \
  $$PWD/../deps/agg/src/agg_sqrt_tables.cpp \
  $$PWD/../deps/agg/src/agg_trans_affine.cpp \
  $$PWD/../deps/agg/src/agg_trans_double_path.cpp \
  $$PWD/../deps/agg/src/agg_trans_single_path.cpp \
  $$PWD/../deps/agg/src/agg_trans_warp_magnifier.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_bspline.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_contour.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_dash.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_markers_term.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_smooth_poly1.cpp \
  $$PWD/../deps/agg/src/agg_vcgen_stroke.cpp \
  $$PWD/../deps/agg/src/agg_vpgen_clip_polygon.cpp \
  $$PWD/../deps/agg/src/agg_vpgen_clip_polyline.cpp \
  $$PWD/../deps/agg/src/agg_vpgen_segmentator.cpp
