
HEADERS += \
  $$PWD/../plugins/input/csv/csv_datasource.hpp \
  $$PWD/../plugins/input/gdal/gdal_featureset.hpp \
  $$PWD/../plugins/input/gdal/gdal_datasource.hpp \
  $$PWD/../plugins/input/geos/geos_datasource.hpp \
  $$PWD/../plugins/input/geos/geos_featureset.hpp \
  $$PWD/../plugins/input/kismet/kismet_featureset.hpp \
  $$PWD/../plugins/input/kismet/kismet_datasource.hpp \
  $$PWD/../plugins/input/kismet/kismet_types.hpp \
  $$PWD/../plugins/input/occi/occi_featureset.hpp \
  $$PWD/../plugins/input/occi/occi_datasource.hpp \
  $$PWD/../plugins/input/occi/occi_types.hpp \
  $$PWD/../plugins/input/occi/spatial_classesh.h \
  $$PWD/../plugins/input/occi/spatial_classesm.h \
  $$PWD/../plugins/input/ogr/ogr_converter.hpp \
  $$PWD/../plugins/input/ogr/ogr_featureset.hpp \
  $$PWD/../plugins/input/ogr/ogr_datasource.hpp \
  $$PWD/../plugins/input/ogr/ogr_layer_ptr.hpp \
  $$PWD/../plugins/input/ogr/ogr_feature_ptr.hpp \
  $$PWD/../plugins/input/ogr/ogr_index.hpp \
  $$PWD/../plugins/input/ogr/ogr_index_featureset.hpp \
  $$PWD/../plugins/input/osm/basiccurl.h \
  $$PWD/../plugins/input/osm/dataset_deliverer.h \
  $$PWD/../plugins/input/osm/osm.h \
  $$PWD/../plugins/input/osm/osmparser.h \
  $$PWD/../plugins/input/osm/osmtagtypes.h \
  $$PWD/../plugins/input/osm/osm_featureset.hpp \
  $$PWD/../plugins/input/osm/osm_datasource.hpp \
  $$PWD/../plugins/input/postgis/connection.hpp \
  $$PWD/../plugins/input/postgis/connection_manager.hpp \
  $$PWD/../plugins/input/postgis/cursorresultset.hpp \
  $$PWD/../plugins/input/postgis/postgis_datasource.hpp \
  $$PWD/../plugins/input/postgis/postgis_featureset.hpp \
  $$PWD/../plugins/input/postgis/resultset.hpp \
  $$PWD/../plugins/input/raster/raster_info.hpp \
  $$PWD/../plugins/input/raster/raster_featureset.hpp \
  $$PWD/../plugins/input/raster/raster_datasource.hpp \
  $$PWD/../plugins/input/rasterlite/rasterlite_include.hpp \
  $$PWD/../plugins/input/rasterlite/rasterlite_featureset.hpp \
  $$PWD/../plugins/input/rasterlite/rasterlite_datasource.hpp \
  $$PWD/../plugins/input/shape/dbffile.hpp \
  $$PWD/../plugins/input/shape/shape.hpp \
  $$PWD/../plugins/input/shape/shape_datasource.hpp \
  $$PWD/../plugins/input/shape/shape_featureset.hpp \
  $$PWD/../plugins/input/shape/shapefile.hpp \
  $$PWD/../plugins/input/shape/shape_index_featureset.hpp \
  $$PWD/../plugins/input/shape/shape_io.hpp \
  $$PWD/../plugins/input/shape/shp_index.hpp \
  $$PWD/../plugins/input/sqlite/sqlite_connection.hpp \
  $$PWD/../plugins/input/sqlite/sqlite_featureset.hpp \
  $$PWD/../plugins/input/sqlite/sqlite_datasource.hpp \
  $$PWD/../plugins/input/sqlite/sqlite_types.hpp

SOURCES += \
  $$PWD/../plugins/input/csv/csv_datasource.cpp \
  $$PWD/../plugins/input/gdal/gdal_featureset.cpp \
  $$PWD/../plugins/input/gdal/gdal_datasource.cpp \
  $$PWD/../plugins/input/geos/geos_datasource.cpp \
  $$PWD/../plugins/input/geos/geos_featureset.cpp \
  $$PWD/../plugins/input/kismet/kismet_featureset.cpp \
  $$PWD/../plugins/input/kismet/kismet_datasource.cpp \
  $$PWD/../plugins/input/occi/occi_featureset.cpp \
  $$PWD/../plugins/input/occi/occi_datasource.cpp \
  $$PWD/../plugins/input/occi/occi_types.cpp \
  $$PWD/../plugins/input/occi/spatial_classesm.cpp \
  $$PWD/../plugins/input/occi/spatial_classeso.cpp \
  $$PWD/../plugins/input/ogr/ogr_converter.cpp \
  $$PWD/../plugins/input/ogr/ogr_featureset.cpp \
  $$PWD/../plugins/input/ogr/ogr_datasource.cpp \
  $$PWD/../plugins/input/ogr/ogr_index_featureset.cpp \
  $$PWD/../plugins/input/osm/basiccurl.cpp \
  $$PWD/../plugins/input/osm/dataset_deliverer.cpp \
  $$PWD/../plugins/input/osm/osm.cpp \
  $$PWD/../plugins/input/osm/osmparser.cpp \
  $$PWD/../plugins/input/osm/osm_featureset.cpp \
  $$PWD/../plugins/input/osm/osm_datasource.cpp \
  $$PWD/../plugins/input/osm/render.cpp \
  $$PWD/../plugins/input/postgis/postgis_datasource.cpp \
  $$PWD/../plugins/input/postgis/postgis_featureset.cpp \
  $$PWD/../plugins/input/raster/raster_info.cpp \
  $$PWD/../plugins/input/raster/raster_featureset.cpp \
  $$PWD/../plugins/input/raster/raster_datasource.cpp \
  $$PWD/../plugins/input/rasterlite/rasterlite_featureset.cpp \
  $$PWD/../plugins/input/rasterlite/rasterlite_datasource.cpp \
  $$PWD/../plugins/input/shape/dbffile.cpp \
  $$PWD/../plugins/input/shape/shape.cpp \
  $$PWD/../plugins/input/shape/shape_datasource.cpp \
  $$PWD/../plugins/input/shape/shape_featureset.cpp \
  $$PWD/../plugins/input/shape/shape_index_featureset.cpp \
  $$PWD/../plugins/input/shape/shape_io.cpp \
  $$PWD/../plugins/input/sqlite/sqlite_featureset.cpp \
  $$PWD/../plugins/input/sqlite/sqlite_datasource.cpp
